name: Deploy web

on:
  push:
    tags:
      - "v*"

jobs:
  deploy-website:
    name: Deploy website
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Setup public path
        run: echo "APP_PUBLIC_PATH=/${{ github.event.repository.name }}/" >> .env

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/
